---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hcloud-fip-k8s.fullname" . }}
  labels:
    {{- include "hcloud-fip-k8s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hcloud-fip-k8s.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hcloud-fip-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hcloud-fip-k8s.fullname" . }}
  labels:
    {{- include "hcloud-fip-k8s.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hcloud-fip-k8s.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hcloud-fip-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
